# Generated by Django 5.2.3 on 2025-06-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                
                ('age', models.IntegerField()),
                ('contract_years', models.IntegerField()),
                ('shift', models.CharField(max_length=100)),
                ('performance', models.FloatField()),
            ],
        ),
    ]
