# Generated by Django 5.2.3 on 2025-06-24 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='123456@company.com', max_length=100),
        ),
    ]
