# Generated by Django 5.2.3 on 2025-06-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='123456@company.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='employee',
            name='shift',
            field=models.CharField(default='Morning', max_length=100),
        ),
    ]
